[config.wallpaper]
command = "notify-send"
arguments = ["-t", "1000", "-e", "Running matugen..."]
set = false

[templates.waybar]
input_path = './templates/waybar.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'sed -i s/i/i/ ~/.config/waybar/style.css'

[templates.wlogout]
input_path = './templates/wlogout.css'
output_path = '~/.config/wlogout/colors.css'

[templates.dunst]
input_path = './templates/dunstrc-colors'
output_path = '~/.config/dunst/dunstrc.d/matugen-colors.conf'
post_hook = 'pgrep -x dunst && dunstctl reload'

[templates.swaync]
input_path = './templates/swaync.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'pgrep -x swaync && swaync-client -rs'

[templates.rofi]
input_path = './templates/rofi.css'
output_path = '~/.config/rofi/colors.rasi'

[templates.midnight-discord]
input_path = './templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/midnight-matugen.css'

[templates.system24-discord]
input_path = './templates/system24-discord.css'
output_path = '~/.config/vesktop/themes/system24-matugen.css'

[templates.kitty-dark]
input_path = './templates/kitty-dark.conf'
output_path = '~/.config/kitty/dark-theme.auto.conf'

[templates.kitty-light]
input_path = './templates/kitty-light.conf'
output_path = '~/.config/kitty/light-theme.auto.conf'
post_hook = 'pgrep -x kitty && pkill -SIGUSR1 kitty'

[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.niri]
input_path = './templates/niri-matugen.kdl'
output_path = '~/.config/niri/matugen-colors.kdl'

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3'

[templates.cava]
input_path = './templates/cava-colors.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = "pgrep -x cava && pkill -USR1 cava"

[templates.yazi]
input_path = './templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.spotify]
input_path = './templates/spotify-color.ini'
output_path = '~/.config/spicetify/Themes/colorful/color.ini'
post_hook = 'pgrep -x spotify && spicetify refresh'

[templates.spotify-text]
input_path = './templates/spotify-text-color.ini'
output_path = '~/.config/spicetify/Themes/text/color.ini'

[templates.hyprlock]
input_path = './templates/hyprlock-colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.vscode]
input_path = './templates/vscode-color-theme.json'
output_path = '~/.vscode-oss/extensions/matugen-vscode/themes/Matugen-color-theme.json'

[templates.zen]
input_path = './templates/userChrome.css'
output_path = '~/.zen/32k6x2yc.Default (release)/chrome/userChrome.css'

[templates.pywalfox]
input_path = './templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'matugen-pywalfox.sh'

[templates.color-scheme]
input_path = './templates/Matugen.colors'
output_path = '~/.local/share/color-schemes/Matugen.colors'
post_hook = 'reload-qt.sh &'
