# : Manager [[[

[mgr]
cwd = { fg = "#171c1f" }

# Tab
tab_active = { fg = "#ffffff", bg = "#116682", bold = true }
tab_inactive = { fg = "#bde9ff", bg = "#001f2a" }
tab_width = 1

# Find
find_keyword = { fg = "#ba1a1a", bold = true, italic = true, underline = true }
find_position = { fg = "#ba1a1a", bold = true, italic = true }

# Marker
marker_copied = { fg = "#8a79ff", bg = "#8a79ff" }
marker_cut = { fg = "#e3dfff", bg = "#e3dfff" }
marker_marked = { fg = "#ba1a1a", bg = "#ba1a1a" }
marker_selected = { fg = "#5d5b7d", bg = "#5d5b7d" }

# Count
count_copied = { fg = "#191836", bg = "#e3dfff" }
count_cut = { fg = "#191836", bg = "#e3dfff" }
count_selected = { fg = "#ffffff", bg = "#5d5b7d" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#116682" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#ffffff", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#116682", fg = "#ffffff", bold = true }
normal_alt  = { bg = "#dce4e9", fg = "#40484c" }

# Select mode
select_main = { bg = "#4d616c", fg = "#ffffff", bold = true }
select_alt  = { bg = "#dce4e9", fg = "#40484c" }

# Unset mode
unset_main = { bg = "#5d5b7d", fg = "#ffffff", bold = true }
unset_alt  = { bg = "#dce4e9", fg = "#40484c" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#116682", bg = "#f6fafd" }
progress_error = { fg = "#ba1a1a", bg = "#f6fafd" }

# Permissions
permissions_t = { fg = "#9badb7" }
permissions_w = { fg = "#afadc4" }
permissions_x = { fg = "#ed8080" }
permissions_r = { fg = "#5d46ff" }
permissions_s = { fg = "#24b6ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#116682" }
active = { fg = "#5d5b7d", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#116682" }
value = { fg = "#171c1f" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#116682", bg = "#ffffff" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#116682" }
title = {}
hovered = { fg = "#e3dfff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#f6fafd" }
cand = { fg = "#116682" }
rest = { fg = "#ffffff" }
desc = { fg = "#171c1f" }
separator = " ‚ñ∂ "
separator_style = { fg = "#171c1f" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#171c1f" }
run = { fg = "#171c1f" }
footer = { fg = "#ffffff", bg = "#4d616c" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#5d5b7d" }
title_warn = { fg = "#116682" }
title_error = { fg = "#ba1a1a" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#ffdad6" },
    { name = "*", is = "exec", fg = "#410002" },

    # Fallback
    { name = "*", fg = "#171c1f" },
    { name = "*/", fg = "#116682" },
]

# : ]]]
